Repository GodotModding/godot-mod-tool, pull requests merged in 2023-04, with the labels that each got.

#50 feat: remove 7zip and let the user download it
  .gitattrubutes
  .gitignore
  addons/mod_tool/global/store.gd
  addons/mod_tool/vendor/7zip/win/zip.exe
Labels: enhancement

#52 fix: :ambulance: unexpected argument type
  addons/mod_tool/global/store.gd
Labels: bug

#54 refactor: change input actions to reference to avoid freeing
  addons/mod_tool/interface/file_system/file_system_context_actions.gd
  addons/mod_tool/plugin.gd
Labels: refactor / cleanup

#55 fix: ✏️ windows/7zz.exe -> windows/7z.exe
  .gitignore
  addons/mod_tool/global/store.gd
Labels: bug
