Repository GodotModding/godot-mod-tool, pull requests merged in 2024-12, with the labels that each got.

#118 feat: :sparkles: added `ModToolInterfaceButtonWithHint`
  addons/mod_tool/interface/global/button_with_hint.gd
  addons/mod_tool/interface/global/button_with_hint.tscn
  addons/mod_tool/interface/panel/tools_panel.tscn
Labels: enhancement, 3.x

#116 refactor: :recycle: removed 7zip dependency
  addons/mod_tool/interface/get_7zip/get_7zip.gd
  addons/mod_tool/interface/get_7zip/get_7zip.tscn
  addons/mod_tool/interface/panel/tools_panel.gd
  addons/mod_tool/interface/panel/tools_panel.tscn
  addons/mod_tool/scripts/build_zip.gd
  addons/mod_tool/scripts/file_system_link.gd
Labels: refactor / cleanup, 3.x

#117 fix: :bug: create 'unpacked-mods' if missing when symlinking
  addons/mod_tool/interface/panel/tools_panel.gd
Labels: bug, 3.x

#111 feat: :sparkles: mod hook gen
  .gitignore
  addons/mod_tool/global/store.gd
  addons/mod_tool/global/utils.gd
  addons/mod_tool/interface/create_mod/create_mod.gd
  addons/mod_tool/interface/file_system/file_system_context_actions.gd
  addons/mod_tool/interface/hook_gen/hook_gen.gd
  addons/mod_tool/interface/hook_gen/hook_gen.tscn
  addons/mod_tool/interface/hook_restore/hook_restore.gd
  addons/mod_tool/interface/hook_restore/hook_restore.tscn
  addons/mod_tool/interface/panel/tools_panel.gd
  addons/mod_tool/interface/panel/tools_panel.tscn
  addons/mod_tool/scripts/hook_gen.gd
Labels: 4.x

#119 feat: add context menu to create a hook file
  addons/mod_tool/interface/file_system/file_system_context_actions.gd
  addons/mod_tool/scripts/build_zip.gd
  addons/mod_tool/scripts/hook_gen.gd
Labels: enhancement, 4.x

#124 refactor: :fire: remove 7zip check
  addons/mod_tool/global/store.gd
Labels: bug, 3.x

#123 v0.2.1
  addons/mod_tool/global/store.gd
  addons/mod_tool/interface/global/button_with_hint.gd
  addons/mod_tool/interface/global/button_with_hint.tscn
  addons/mod_tool/interface/panel/tools_panel.gd
  addons/mod_tool/interface/panel/tools_panel.tscn
Labels: release, 3.x
